AllCops:
  TargetRubyVersion: 2.6

Style/FormatStringToken:
  EnforcedStyle: template

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/LineLength:
  Max: 124
  AllowURI: true
  URISchemes:
    - http
    - https
  IgnoredPatterns: ['\A(?:\s)*?#']

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
